CREATE OR REPLACE TRIGGER io_delete
INSTEAD OF DELETE ON aspire_systems
FOR EACH ROW
BEGIN
  DELETE FROM trainer WHERE FULL_NAME = :old.FULL_NAME;
  DELETE FROM subject WHERE SUBJECT_NAME= :old.SUBJECT_NAME;
END;
/

DELETE FROM aspire_systems WHERE FULL_NAME = 'Anitha Manogaran';