SET SERVEROUTPUT ON;
DECLARE
   v_pi CONSTANT NUMBER := 3.141592;
BEGIN
  DBMS_OUTPUT.PUT_LINE(v_pi);
END;
/

DECLARE
   v_pi CONSTANT NUMBER NOT NULL DEFAULT 3.141592;
BEGIN
  DBMS_OUTPUT.PUT_LINE(v_pi);
END;

